/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.raven.form;

import Controller.GuestControl;
import Model.Guest;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NGUYEN PHUC NAM
 */
public class FormKhachHang extends javax.swing.JFrame {

    private final ArrayList<Guest> listGuests = GuestControl.getlistGuests();
    DefaultTableModel model;

    /**
     * Creates new form FormKhachHang
     */
    public FormKhachHang() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
//        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        model = (DefaultTableModel) jTable1.getModel();
        jID.setText(GuestControl.ReturnNextID());
        jID.enable(false);
        ButtonGroup g = new ButtonGroup();
        g.add(jNu);
        g.add(jNam);
        showTable();
    }

    public final void showTable() {
        for (Guest e : listGuests) {
            if (e.getGender() == 1) {
                model.addRow(new Object[]{
                    e.getId(), e.getName(), "Nam", e.getIdCard(), e.getPhone(), e.getBirthday()
                });

            } else {
                model.addRow(new Object[]{
                    e.getId(), e.getName(), "Nữ", e.getIdCard(), e.getPhone(), e.getBirthday()
                });
            }
        }
    }

    public void showResult() {
        Guest e = listGuests.get(listGuests.size() - 1);
        Date date = e.getBirthday();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        if (e.getGender() == 1) {
            model.addRow(new Object[]{
                e.getId(), e.getName(), "Nam", e.getIdCard(), e.getPhone(), dateFormat.format(e.getBirthday())
            });

        } else {
            model.addRow(new Object[]{
                e.getId(), e.getName(), "Nữ", e.getIdCard(), e.getPhone(), dateFormat.format(e.getBirthday())
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jIdCard = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jNam = new javax.swing.JRadioButton();
        jNu = new javax.swing.JRadioButton();
        jThem = new javax.swing.JButton();
        jsua = new javax.swing.JButton();
        jXoa = new javax.swing.JButton();
        jLamMoi = new javax.swing.JButton();
        jBirthDay = new com.toedter.calendar.JDateChooser();
        jName = new javax.swing.JTextField();
        jPhone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setText("Mã Khách Hàng");

        jLabel2.setText("Tên Khách Hàng");

        jLabel3.setText("Ngày sinh");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng", "Giới Tính", "Số CCCD", "Số Điện Thoại", "Ngày Sinh"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("CCCD");

        jLabel5.setText("Số Điện Thoại");

        jLabel6.setText("Giới Tính ");

        jNam.setText("Nam ");

        jNu.setText("Nữ");

        jThem.setText("Thêm");
        jThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jThemActionPerformed(evt);
            }
        });

        jsua.setText("Sửa");
        jsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsuaActionPerformed(evt);
            }
        });

        jXoa.setText("Xóa");
        jXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXoaActionPerformed(evt);
            }
        });

        jLamMoi.setText("Làm mới");
        jLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jID, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jBirthDay, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jIdCard, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jNam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jNu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(12, 12, 12))))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLamMoi)
                            .addComponent(jsua, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jID, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jName, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBirthDay, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jIdCard, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jNam)
                    .addComponent(jNu))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jThem)
                    .addComponent(jsua))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLamMoi)
                    .addComponent(jXoa))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLamMoiActionPerformed
        // TODO add your handling code here:
        jID.setText(GuestControl.ReturnNextID());
        jName.setText("");
        jIdCard.setText("");
        jNam.setSelected(false);
        jNu.setSelected(false);
        jBirthDay.setDate(null);
        jPhone.setText("");
        jTable1.clearSelection();
    }//GEN-LAST:event_jLamMoiActionPerformed

    private void jXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXoaActionPerformed
        // TODO add your handling code here:
        int t = jTable1.getSelectedRow();
        if (t == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn khách hàng cần xóa");
        } else {
            int cf = JOptionPane.showConfirmDialog(null,
                    "Bạn có muốn xóa khách hàng này không?", "Xác Nhận", JOptionPane.YES_NO_OPTION);
            if (cf == 0) {
                GuestControl.Remove(jTable1.getValueAt(t, 0).toString());
                model.removeRow(t);
                jTable1.updateUI();
            }

        }
    }//GEN-LAST:event_jXoaActionPerformed

    private void jsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsuaActionPerformed
        // TODO add your handling code here:
        String id = jID.getText();
        String name = jName.getText();
        String idCard = jIdCard.getText();
        int gender = -1;
        if (jNam.isSelected()) {
            gender = 1;
        } else if (jNu.isSelected()) {
            gender = 0;
        }
        Date Bdate = jBirthDay.getDate();
        String phone = jPhone.getText();
        try {
            long x = Integer.parseInt(idCard.substring(0, 7));
            long z = Integer.parseInt(idCard.substring(7, idCard.length()));
            long y = Integer.parseInt(phone.substring(0, 7));
            long y1 = Integer.parseInt(phone.substring(7, phone.length()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "CMND hoặc số điện thoại không hợp lệ");
            return;
        }
        int i = jTable1.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn khách hàng cần sửa");
        } else {
            int check = GuestControl.edit(id, name, idCard, gender, Bdate, phone);
            switch (check) {
                case 1 -> {
                    JOptionPane.showMessageDialog(null, "Sửa thông tin thành công");
                    jTable1.setValueAt(name, i, 1);
                    jTable1.setValueAt(idCard, i, 3);
                    if (jNam.isSelected()) {
                        jTable1.setValueAt("Nam", i, 2);
                    } else if (jNu.isSelected()) {
                        jTable1.setValueAt("Nữ", i, 2);
                    }
                    java.sql.Date sqlDate = new java.sql.Date(Bdate.getTime());
                    jTable1.setValueAt(sqlDate, i, 5);
                    jTable1.setValueAt(phone, i, 4);
                    jTable1.updateUI();
                }
                case -1 ->
                    JOptionPane.showMessageDialog(null, "Khách hàng không đủ tuổi");

                case 0 ->
                    JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi, vui lòng thử lại");
                default ->
                    throw new AssertionError();
            }
        }
    }//GEN-LAST:event_jsuaActionPerformed

    private void jThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jThemActionPerformed
        // TODO add your handling code here:
        String id = jID.getText();
        String name = jName.getText();
        String idCard = jIdCard.getText();
        int gender = -1;
        if (jNam.isSelected()) {
            gender = 1;
        } else if (jNu.isSelected()) {
            gender = 0;
        }
        Date Bdate = jBirthDay.getDate();
        String phone = jPhone.getText();
        int check = GuestControl.check(id, name, idCard, gender, Bdate, phone);
        switch (check) {
            case -1 ->
                JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
            case -2 ->
                JOptionPane.showMessageDialog(null, "Bấm làm mới trước khi thêm nhân viên mới");
            case -3 ->
                JOptionPane.showMessageDialog(null, "Số chứng minh nhân dân bị trùng lặp");
            case -4 ->
                JOptionPane.showMessageDialog(null, "CMND hoặc số điện thoại không hợp lệ");
            case -5 ->
                JOptionPane.showMessageDialog(null, "Khách Hàng Không Đủ Tuổi");
            case 1 -> {
                JOptionPane.showMessageDialog(null, "Thêm thành công!");
                Guest e = new Guest();
                e.setId(id);
                e.setName(name);
                e.setIdCard(idCard);
                e.setGender(gender);
                e.setPhone(phone);
                e.setBirthday(Bdate);

                listGuests.add(e);
                showResult();
                jID.setText(GuestControl.ReturnNextID());
            }
            default ->
                throw new AssertionError();
        }
    }//GEN-LAST:event_jThemActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int vitri = jTable1.getSelectedRow();
        jID.setText(jTable1.getValueAt(vitri, 0).toString());
        jName.setText(jTable1.getValueAt(vitri, 1).toString());
        jIdCard.setText(jTable1.getValueAt(vitri, 3).toString());
        if (jTable1.getValueAt(vitri, 2).equals("Nam")) {
            jNam.setSelected(true);
        } else {
            jNu.setSelected(true);
        }
        try {
            jBirthDay.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(jTable1.getValueAt(vitri, 5).toString()));
        } catch (ParseException ex) {
            Logger.getLogger(FormNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        jPhone.setText(jTable1.getValueAt(vitri, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jBirthDay;
    private javax.swing.JTextField jID;
    private javax.swing.JTextField jIdCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jLamMoi;
    private javax.swing.JRadioButton jNam;
    private javax.swing.JTextField jName;
    private javax.swing.JRadioButton jNu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPhone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jThem;
    private javax.swing.JButton jXoa;
    private javax.swing.JButton jsua;
    // End of variables declaration//GEN-END:variables
}
